### ISSUE TITLE
Milestones (Etappen)

### ISSUE THREAD

**Issue by MackieLoeffel** [MackieLoeffel/weltfairsteher#2]
15 - 20 points steps
- [x] configureable via admin
- [x] show progress in table
- [x] show in chart
